name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: 'read'
     id-token: 'write'
     issues: 'write'

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
